In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,classification_report
import seaborn as sns

In [32]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"
columns = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

In [33]:
df = pd.read_csv(url,header=None,names=columns,na_values='?')
df.head(7)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
5,56.0,1.0,2.0,120.0,236.0,0.0,0.0,178.0,0.0,0.8,1.0,0.0,3.0,0
6,62.0,0.0,4.0,140.0,268.0,0.0,2.0,160.0,0.0,3.6,3.0,2.0,3.0,3

In [34]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          4
thal        2
target      0
dtype: int64

In [35]:
df.dropna(inplace=True)

In [36]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [37]:
df["target"] = (df["target"] > 0).astype(int)

In [38]:
x = df.drop(columns=['target'])
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57.0,0.0,4.0,140.0,241.0,0.0,0.0,123.0,1.0,0.2,2.0,0.0,7.0
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0

In [39]:
y = df.target
y

0      0
1      1
2      1
3      0
4      0
      ..
297    1
298    1
299    1
300    1
301    1
Name: target, Length: 297, dtype: int32

In [40]:
params_svm = {
    "kernel" : "linear",
    "C" : 1.0,
    "gamma" : "scale"
}

In [41]:
params_rfc = {
    "n_estimators" : 100,
    "max_depth" : 3,
    "random_state" : 43
}

In [42]:
def model_training(x,y,classifier):
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=43,stratify=y)
    scaler = StandardScaler()
    x_train = scaler.fit_transform(x_train)
    x_test = scaler.transform(x_test)
    model = classifier.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    accuracy = accuracy_score(y_test,y_pred)
    c_report = classification_report(y_test,y_pred)
    return accuracy,c_report,y_test,y_pred

In [43]:
svm = SVC(**params_svm)

In [44]:
accuracy_svm, classification_report_svm,y_test_svm,y_pred_svm = model_training(x,y,svm)
print(f"The accuracy of SVM model is: {accuracy_svm*100:.2f}")

The accuracy of SVM model is: 85.56

In [45]:
print(classification_report_svm)

              precision    recall  f1-score   support

           0       0.83      0.92      0.87        48
           1       0.89      0.79      0.84        42

    accuracy                           0.86        90
   macro avg       0.86      0.85      0.85        90
weighted avg       0.86      0.86      0.85        90

In [46]:
rfc = RandomForestClassifier(**params_rfc)

In [47]:
accuracy_rfc, classification_report_rfc,y_test_rfc,y_pred_rfc = model_training(x,y,rfc)
print(f"The accuracy of Random Forest Classifier model is: {accuracy_rfc*100:.2f}")

The accuracy of Random Forest Classifier model is: 83.33

In [48]:
print(classification_report_rfc)

              precision    recall  f1-score   support

           0       0.79      0.94      0.86        48
           1       0.91      0.71      0.80        42

    accuracy                           0.83        90
   macro avg       0.85      0.83      0.83        90
weighted avg       0.85      0.83      0.83        90

In [49]:
report_svm = classification_report(y_test_svm,y_pred_svm,output_dict=True)
report_svm

{'0': {'precision': 0.8301886792452831,
  'recall': 0.9166666666666666,
  'f1-score': 0.8712871287128713,
  'support': 48},
 '1': {'precision': 0.8918918918918919,
  'recall': 0.7857142857142857,
  'f1-score': 0.8354430379746834,
  'support': 42},
 'accuracy': 0.8555555555555555,
 'macro avg': {'precision': 0.8610402855685875,
  'recall': 0.8511904761904762,
  'f1-score': 0.8533650833437774,
  'support': 90},
 'weighted avg': {'precision': 0.8589835118137005,
  'recall': 0.8555555555555555,
  'f1-score': 0.8545598863683835,
  'support': 90}}

In [50]:
report_rfc = classification_report(y_test_rfc,y_pred_rfc,output_dict=True)
report_rfc

{'0': {'precision': 0.7894736842105263,
  'recall': 0.9375,
  'f1-score': 0.8571428571428572,
  'support': 48},
 '1': {'precision': 0.9090909090909091,
  'recall': 0.7142857142857143,
  'f1-score': 0.8,
  'support': 42},
 'accuracy': 0.8333333333333334,
 'macro avg': {'precision': 0.8492822966507176,
  'recall': 0.8258928571428572,
  'f1-score': 0.8285714285714286,
  'support': 90},
 'weighted avg': {'precision': 0.8452950558213717,
  'recall': 0.8333333333333334,
  'f1-score': 0.8304761904761905,
  'support': 90}}

In [51]:
svm_classifier = {
    'model_name' : 'Support Vector Machine',
    'params' : params_svm,
    'metrics' : report_svm,
    'model' : svm
}

In [52]:
random_forest = {
    'model_name' : 'Random Forest Classifier',
    'params': params_rfc,
    'metrics' : report_rfc,
    'model' : rfc
}

In [53]:
models = [svm_classifier,random_forest]

In [54]:
import mlflow

In [55]:
mlflow.set_experiment("MLOps Experiment 1")

<Experiment: artifact_location=('file:///D:/Workspace/MLOps Exercise/MLflow/Experiment '
 '1/mlruns/327305762615529764'), creation_time=1785776973814, experiment_id='327305762615529764', last_update_time=1785776973814, lifecycle_stage='active', name='MLOps Experiment 1', tags={}>

In [56]:
mlflow.set_tracking_uri(uri="http://localhost:5000")

In [57]:
for i,element in enumerate(models):
    model_name = element['model_name']
    params = element['params']
    metrics = element['metrics']
    model = element['model']
    with mlflow.start_run(run_name=model_name):
        mlflow.log_params(params)
        mlflow.log_metrics({
            'accuracy' : metrics['accuracy'],
            'recall_no_heart_disease' : metrics['0']['recall'],
            'recall_heart_disease' : metrics['1']['recall'],
            'precision_no_heart_disease' : metrics['0']['precision'],
            'precision_heart_disease' : metrics['1']['precision'],
            'f1_score_macro' : metrics['macro avg']['f1-score']
        })
        mlflow.sklearn.log_model(model,model_name)

E:\tf_gpu_venv\py310\lib\site-packages\_distutils_hack\__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
E:\tf_gpu_venv\py310\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")